pipelines:
  default:
    - step:
        name: Sync GitHub Mirror
        image: alpine/git:latest
        clone:
          enabled: false
        script:
          - git clone --bare git@bitbucket.org:vuvo262/practice-ui.git
          - cd practice-ui.git
          - git push --mirror git@github.com:hoangvu98262/practice-ui-web.git